language: go
install: true
script: make build
addons:
  ssh_known_hosts:
  - "$HOST"
after_success:
- rsync -av -e "ssh -o StrictHostKeyChecking=no" output/linux/* home@$HOST:/home/home/test
notifications:
  email:
    recipients:
    - cn100800@163.com
    on_success: always
    on_failure: always
deploy:
  provider: releases
  api_key:
    secure: ZXFkOD4xsSQIektxxjp6Y8INeHcUzvIk7tl2IxhfANnadTErzihlJY8FXnQCC4B2VFv64iGy7xbhH8Rxs8sr3K9/9AGnWDwwuF2d/mGQvX6EcDqNS7uoF65ErEVf+Ym7MVzbWmh0stnyPmB/3rRWaB9343ZaC5WWK7XMhzG+vkXqmIo6D+yDjyC5+OSEpHtMucVyf/o22+dTARuRqyIfMWe3Y5/XW3HxiUlykN85C1r442VcnKn8uLV20DDigM3tKqG5BjAtkhL45DSC8YPvczEhCupC4lwbHS3gY5Qkz82o356QryVzJf17o/o9cQrmVPKKWS6SewC8JJewsWfJy5ZF3/11nX/Zs9SIaQ2WzgoMYyP2W1aLrtoBj8LdrdTYXrpVUWztPsMTqe6zlUJc4jQ0lJBwD5J8EFn+3HeuePiZ+QthODuRrSVf7/Ve6I5ohgxcG5uu8Mesnimfc1xzm1bXojKkk3cQzjbhB9iy5kFH/Dw9tw6cwf6lLL8/c6ZIjhs9zJDdxRSAzojWMK8H9o3aPjSrtXEbCUij0CY8+WXiXhdxFWDelXwNeMeO91Vntbz/uq1swr82WCZHyPxCOiMiAIluC5dh+t9bBdwEysbSxVXQNphMZ8HUSyy91R1pYoK1hxslhajNbYP2sN/7HLAjhvpcM0ekr0vjSiXspMw=
  file_glob: true
  file:
  - release/*
  skip_cleanup: true
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_2c6b8603e1ab_key -iv $encrypted_2c6b8603e1ab_iv
  -in cn.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
