name: Go

on:
  push:
  schedule:
    - cron: "50 15 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: go build

      - name: Test
        env:
          G_TOKEN: ${{ secrets.PUSH_TOKEN }}
        run: |
          /home/runner/work/news/news/news
          git clone https://github.com/freecracy/daily.git /home/runner/work/news/daily
          mkdir -p /home/runner/work/news/daily/docs/`TZ=UTC-8 date +%Y-%Y-%m`
          mv `TZ=UTC-8 date +%Y-%m-%d-news.md` /home/runner/work/news/daily/docs/`TZ=UTC-8 date +%Y-%Y-%m`
          cd /home/runner/work/news/daily
          git config user.name freecracy
          git config user.email 12114073+freecracy@users.noreply.github.com
          git add .
          git commit -m `TZ=UTC-8 date +%Y-%m-%d`
          git push https://${G_TOKEN}@github.com/freecracy/daily.git main:main
